

- name: lizard master
  hosts: lizard-masters
  roles:
    - common
    - lizard-common
    - lizard-master
  become: yes


- name: lizard chunk servers
  hosts: lizard-chunks
  roles:
    - common
    - lizard-common
    - lizard-chunk